---
name: CheckIP
version: "1.0.1"
slug: checkip
description: "Self-hosted tiny web-page allowing you to get Internet IP address you are using"
url: "https://github.com/banditto9/addon-checkip/"
arch:
  - aarch64
  - amd64
init: false
webui: "http://[HOST]:[PORT:80]"
ports:
  80/tcp: 85
ports_description:
  80/tcp: Web
